apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blueorgreen
    hint: nonpremium
  name: blueorgreen-nonpremium
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blueorgreen
    hint: nonpremium
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blueorgreen
    hint: premium
  name: blueorgreen-premium
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blueorgreen
  type: ClusterIP
status:
  loadBalancer: {}
